### ISSUE TITLE
Run and test

### ISSUE THREAD

**Issue by anhpham197** [deiruch/kissat#4]
I've tested some problems with the original Kissat version on Ubuntu, but I wanna try to use your version for Windows. Hence, can you guide me on how to build and run test your version on Windows? I saw two files `kissat.dll` and `kissat.exe` in your latest version (3.0.0) but when I typed on file `kissat.exe`, and then pressed **Enter**, it closed without result. 
Thanks for your contribution!

**Comment by deiruch** [comment]
That is surprising. When you double-click `kissat.exe` you should see the following output, and the window shouldn't close automatically:
![image](https://user-images.githubusercontent.com/4119188/229349921-cf1bc043-4a96-4539-8d8f-2f384103716c.png)

You don't see this? Also, you don't get an error message? What happens when you run `kissat.exe` from the command line?

**Comment by anhpham197** [comment]
Dear @deiruch , I could see this window as in the image above when double-clicking the file `kissat.exe`. However, if `kissat.exe` is the output, where is the input file put? I mean in general, to run a cnf file (your version in Windows), where should I put cnf file and where I can file the output of that file?

**Comment by deiruch** [comment]
It's a command line application. Instead of double-clicking it, you should start it from the command line, just as you would in Linux.

**Comment by deiruch** [comment]
You don't need to configure, build or test for Windows. Just run `kissat yourfile.cnf`.

**Comment by deiruch** [comment]
In my tests there was no discernible performance difference. YMMV
